"""define foreign keys

Revision ID: 5a50097638b6
Revises: 50bc2928c41c
Create Date: 2022-07-15 04:04:23.926240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a50097638b6'
down_revision = '50bc2928c41c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_amount', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'budget_amount', 'budget_category', ['category_id'], ['id'])
    op.add_column('budget_item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'budget_item', 'budget_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget_item', type_='foreignkey')
    op.drop_column('budget_item', 'category_id')
    op.drop_constraint(None, 'budget_amount', type_='foreignkey')
    op.drop_column('budget_amount', 'category_id')
    # ### end Alembic commands ###
